### ISSUE TITLE
Sync submodules March 2020

### ISSUE THREAD

**Issue by BinLiu-NOAA** [NOAA-EMC/HAFS#41]
Sync HAFS submodules with their latest develop or master branches.

**Comment by BinLiu-NOAA** [comment]
I have synced all the hafs submodules with their latest develop or master branches in the hafs-community fork's feature/sync_submodule_20200324 ([link](https://github.com/hafs-community/HAFS/tree/feature/sync_submodule_20200324)). Trying to build and test this branch right now.

**Comment by BinLiu-NOAA** [comment]
Hi @ChunxiZhang-NOAA @JiliDong-NOAA and @AndrewHazelton,

My build on Hera failed with this kind of error:

INFO: Checking optional arguments in physics schemes ...
INFO: Metadata table for model FV3 written to /scratch1/NCEPDEV/hwrf/save/Bin.Liu/hafs_202003/sorc/hafs_forecast.fd/FV3/ccpp/framework/doc/DevelopersGuide/CCPP_VARIABLES_FV3.tex
INFO: Comparing metadata for requested and provided variables ...
ERROR: Variable atmosphere_momentum_diffusivity requested by MODULE_satmedmfvdifq SCHEME_satmedmfvdifq SUBROUTINE_satmedmfvdifq_run & MODULE_hedmf_hafs SCHEME_hedmf_hafs SUBROUTINE_hedmf_hafs_run not provided by the model

@ChunxiZhang-NOAA could you please help to check out this hafs-community fork's feature/sync_submodule_20200324 ([link](https://github.com/hafs-community/HAFS/tree/feature/sync_submodule_20200324)) and give it try to see if I have missed something during the merge/sync of the submodules?

Thanks!

Bin

**Comment by AndrewHazelton** [comment]
Bin,

Hmmmm, I got that error at one point when the dkudiagnostic variable in
GFS_typedefs.meta under hafs_forecast.fd/FV3/gfsphysics/GFS_layer/ didn't
match with:

hafs_forecast.fd/FV3/ccpp/physics/physics/satmedmfvdifq.meta


But that was corrected in the version I submitted in the pull request.


Andy

**Comment by AndrewHazelton** [comment]
Did part of my pull request for the GFS_layer part not make it through?

https://github.com/hafs-community/fv3atm/tree/abe496657239840aabaaff3c3c38e84ffa86e10f/gfsphysics/GFS_layer

I'm looking at GFS_typedefs.meta and I do not see the "dkudiagnostic"
variable I defined.

**Comment by BinLiu-NOAA** [comment]
Hi Andy,

I could not see the dkudiagnostic in the GFS_typedefs.meta file either.
Could you please point me to a branch, which has this in the
GFS_typedefs.meta file?

I can try to compare the branches and see if I can pull over the changes.

Thanks!

Bin
---
Bin Liu
IMSG at NOAA/NWS/NCEP/EMC
5830 University Research CT
Cubicle 2026
College Park, MD 20740
Tel: (301)-683-3763
Email: Bin.Liu@noaa.gov

**Comment by BinLiu-NOAA** [comment]
Hi @AndrewHazelton, 

I could not see the dkudiagnostic in the GFS_typedefs.meta file either. Could you please point me to a branch, which has this in the GFS_typedefs.meta file?

I can try to compare the branches and see if I can pull over the changes.

Thanks!

Bin

**Comment by AndrewHazelton** [comment]
Here, it's in this branch:

https://github.com/hafs-community/fv3atm/tree/feature/add_km/gfsphysics/GFS_layer

That should have the correct GFS_typedefs.meta

Let me know if there's a problem.

Andy

**Comment by BinLiu-NOAA** [comment]
Thanks @AndrewHazelton !

I have merged the changes you just committed from this feature/add_km branch. The build is working now. At least, it has passed the previous failure point. Will let you know if I encounter other issues.

Thanks!

Bin

**Comment by AndrewHazelton** [comment]
Thanks - keep me posted!

**Comment by BinLiu-NOAA** [comment]
Dear All, 

@AndrewHazelton @JiliDong-NOAA @ChunxiZhang-NOAA @BijuThomas-NOAA @ZhanZhang-NOAA 

The regression tests on Hera went through well. The develop branch is thus updated. And all the HAFS submodules in the develop branch have now been synced with their latest develop/master branches.

Issue closed.

Thanks!

Bin
